name: "Blog·Leo Li"
description: "Leo Li's blog, focus on Linux, Python, software compilation and so on."
url: "http://ldjhust.github.io"
markdown: kramdown
kramdown:
  input: GFM
exclude: ["*.bak"]
permalink: /:year/:month/:day/:title.html
